package enums;

public class CardName {
    public static String[] list;

    static {
        list = new String[] {
                "Wrestlers",
                "Battle Honors",
                "Bear Traps",
                "Longbows",
                "Keep",
                "Pressgangs",
                "Garrison",
                "Scouts",
                "Alchemist",
                "Martial Culture",
                "Errand Boy",
                "Mercenaries",
                "Tinker\"s Fair",
                "Rain Boots",
                "A Small Favor",
                "Second Wind",
                "Sleight of Hand",
                "Key to the City",
                "Scryer",
                "Disgraced Captain",
                "Naysayers",
                "Book Burning",
                "Ancient Binding",
                "Horse Archers",
                "Warning Signals",
                "Elders",
                "The Gathering",
                "Faithful Friend",
                "Tents",
                "Great Herd",
                "Fire Talkers",
                "Magician\"s Code",
                "Spirit Snare",
                "Wizard School",
                "Dazzle",
                "Acting Troupe",
                "Taming Charm",
                "Inquisitor",
                "Wolves",
                "Animal Playmates",
                "True Names",
                "The Old Oak",
                "Forest Paths",
                "Long-Lost Heir",
                "Rangers",
                "Roving Terror",
                "Wayside Inn",
                "Extra Provisions",
                "Memory of Home",
                "Welcoming Party",
                "Traveling Doctor",
                "Storyteller",
                "Armed Mob",
                "Tavern Songs",
                "Secret Signal",
                "Augury",
                "Rusting Ray",
                "Portal",
                "Billowing Fog",
                "Kindred Warriors",
                "Terror Spells",
                "Blood Pact",
                "Revelation",
                "Observatory",
                "Plague Engines",
                "Gleaming Armor",
                "Bewitch",
                "Jinx",
                "Tutor",
                "Dream Thief",
                "Cracking Ground",
                "Sealing Ward",
                "Initiation Rite",
                "Vow of Silence",
                "Forgotten Vault",
                "Map Library",
                "Witch\"s Bargain",
                "Master of Disguise",
                "Charlatans",
                "Assassin",
                "Downtrodden",
                "Blackmail",
                "Cracked Sage",
                "Dissent",
                "False Prophet",
                "Vow of Renewal",
                "Zealots",
                "Royal Ambitions",
                "Salt the Earth",
                "Beast Tamer",
                "Riots",
                "Silver Tongue",
                "Gambling Hall",
                "Boiling Lake",
                "Relic Thief",
                "Enchantress",
                "Insomnia",
                "Sneak Attack",
                "Gossip",
                "Bandit Chief",
                "Chaos Cult",
                "Slander",
                "Code of Honor",
                "Outriders",
                "Messenger",
                "Field Promotion",
                "Palanquin",
                "Shield Wall",
                "Military Parade",
                "Tome Guardians",
                "Tyrant",
                "Secret Police",
                "Forced Labor",
                "Specialist",
                "Captains",
                "Siege Engines",
                "Royal Tax",
                "Toll Roads",
                "Curfew",
                "Knights Errant",
                "Vow of Obedience",
                "Hunting Party",
                "Council Seat",
                "Encirclement",
                "Peace Envoy",
                "Relic Hunter",
                "Homesteaders",
                "Crop Rotation",
                "A Round of Ale",
                "Land Warden",
                "Charming Friend",
                "Village Constable",
                "Family Heirloom",
                "News from Afar",
                "Levelers",
                "Fabled Feast",
                "The Great Levy",
                "Hearts and Minds",
                "Relic Breaker",
                "Book Binders",
                "Ballot Box",
                "Saddle Makers",
                "Squires",
                "Rowdy Pub",
                "Vow of Peace",
                "Deed Writer",
                "Salad Days",
                "Marriage",
                "Hospital",
                "Awaited Return",
                "Convoys",
                "Vow of Kinship",
                "Wild Mounts",
                "Lancers",
                "Mountain Giant",
                "Rival Khan",
                "Lost Tongue",
                "Special Envoy",
                "Homesick",
                "Oracle",
                "Pilgrimage",
                "Spell Breaker",
                "Mounted Patrol",
                "Great Crusade",
                "Ancient Bloodline",
                "Ancient Pact",
                "Storm Caller",
                "Family Wagon",
                "Way Station",
                "Twin Brother",
                "Hospitality",
                "A Fast Steed",
                "Relic Worship",
                "Sacred Ground",
                "Nature Worship",
                "Birdsong",
                "Small Friends",
                "Grasping Vines",
                "Threatening Roar",
                "Fae Merchant",
                "Second Chance",
                "Pied Piper",
                "Mushrooms",
                "Insect Swarm",
                "Vow of Union",
                "Giant Python",
                "War Tortoise",
                "New Growth",
                "Wild Cry",
                "Animal Host",
                "Memory of Nature",
                "Marsh Spirit",
                "Vow of Poverty",
                "Forest Council",
                "Walled Garden",
                "Vow of Beast-kin",
                "Bracken",
                "Wild Allies",

                // Edifices and ruins
                "Sprawling Rampart",
                "Bandit Rampart",
                "Hall of Debate",
                "Hall of Liberation",
                "Forest Temple",
                "Ruined Temple",
                "Festival District",
                "Squalid District",
                "Great Spire",
                "Fallen Spire",
                "Ancient Forge",
                "Broken Forge",

                // Visions
                "Dynasty",
                "Rebellion",
                "Conspiracy",
                "Faith",
                "Conquest",

                // Note that 215 and 216 were formerly reserved for privilege cards
                "The Darkest Secret",
                "The People\"s Favor / The Mob\"s Favor",

                // Relics
                // Note that 217 was formerly the darkest secret
                "", // VS: skip in index (217)
                "Sticky Fire",
                "Cursed Cauldron",
                "Brass Horse",
                "Truthful Harp",
                "Grand Mask",
                "Horned Mask",
                "Cup of Plenty",
                "Whistle",
                "Dowsing Sticks",
                "Cracked Horn",
                "Bandit Crown",
                "Ring of Devotion",
                "Skeleton Key",
                "Oracular Pig",
                "Circlet of Command",
                "Ivory Eye",
                "Map",
                "Obsidian Cage",
                "Book of Records",
                "Dragonskin Drum", // 237
                "",
                "",
                "", // 240
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "", // 250
                "",
                "",
                "",
                "",

                "NONE" // 255
        };
    }
}
